### ISSUE TITLE
Create a default notification icons.

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/SimpleQmlNotify#2]
Need create a 4 default icons for notification in blender.
1. Question 
2. Information
3. Warning
4. Error

Icons style:  Material

For example:
GNOME have a some as this icons.

![изображение](https://user-images.githubusercontent.com/12465465/104959078-66604c00-59e2-11eb-8ecc-6a5cd0ac2d27.png)

But these icons are deprecated and do not match the Material style.

You can make icons in the style of QuasarApp, but if you come up with something new and interesting it will be very cool.

Material style [example](https://doc.qt.io/qt-5/qtquickcontrols2-material.html)

**Comment by zig1hai** [comment]
done.
